# Databricks notebook source
# NTT DATA 2026
# MAGIC %md
# MAGIC # SV_REGLAS_CALIDAD — Carga de 85 reglas de calidad
# MAGIC
# MAGIC Inserta o actualiza (MERGE) los 85 registros del catálogo de reglas
# MAGIC en la tabla `uc-axa-cli.silver.sv_reglas_calidad`.

# COMMAND ----------
# MAGIC %md
# MAGIC ## Bloque 1 — Configuración

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import (
    StructType, StructField,
    LongType, StringType, IntegerType, DateType
)
from datetime import datetime, timezone

spark = SparkSession.builder.getOrCreate()

TARGET = "`uc-axa-cli`.`silver`.`sv_reglas_calidad`"
LOAD_TS = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")

print(f"Destino : {TARGET}")
print(f"Inicio  : {LOAD_TS}")

# COMMAND ----------
# MAGIC %md
# MAGIC ## Bloque 2 — Datos del catálogo (85 reglas)
# MAGIC
# MAGIC Orden de columnas:
# MAGIC `sk_regla_calidad, pk_regla_calidad, tabla, atributo, tipo_regla,
# MAGIC  regla, grupo_regla, prioridad_regla, estado_regla,
# MAGIC  fecha_ini_vigencia, fecha_fin_vigencia, fecha_actualizacion,
# MAGIC  hash_registro, fecha_creacion`

SCHEMA = StructType([
    StructField("sk_regla_calidad",   LongType(),    False),
    StructField("pk_regla_calidad",   StringType(),  False),
    StructField("tabla",              StringType(),  True),
    StructField("atributo",           StringType(),  True),
    StructField("tipo_regla",         StringType(),  True),
    StructField("regla",              StringType(),  True),
    StructField("grupo_regla",        StringType(),  True),
    StructField("prioridad_regla",    IntegerType(), True),
    StructField("estado_regla",       IntegerType(), True),
    StructField("fecha_ini_vigencia", DateType(),    True),
    StructField("fecha_fin_vigencia", DateType(),    True),
    StructField("fecha_actualizacion",DateType(),    True),
    StructField("hash_registro",      StringType(),  True),
    StructField("fecha_creacion",     DateType(),    True),
])

RAW_DATA = [
    (1, "TD - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Tipo de Documento", "Campo", "tipo_documento IS NULL\nOR TRIM(UPPER(tipo_documento)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' ')", "Se considera como campo vacío si contiene: NULL, \"NULL\", \"0\", \"NE\", \"NO ESPECIFICA\", \"NO TIENE\", \"NA\", \"\", \" \", o cualquier valor relacionado con la ausencia del dato.", 1, 1, "2026-06-01", None, "2026-06-01", "b4034be23e91a7f214b56d76ae1d8967", "2026-06-01"),
    (2, "TD - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Tipo de Documento", "Campo", "tipo_documento IS NOT NULL\nAND UPPER(TRIM(tipo_documento)) NOT IN ('CC','TI','RC','NIT','CE','PS','PPT')", "Este atributo puede ser visto de dos formas, en abreviatura y en descripción, ambos casos son válidos y medirán de forma individual. Los valores válidos son: CC, TI, RC, NIT, CE, PS, PPT.", 2, 1, "2026-06-01", None, "2026-06-01", "40b7cb986043d6883c9ebb88effdadbb", "2026-06-01"),
    (3, "ND - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Número Documento", "Campo", "num_documento IS NULL\nOR TRIM(UPPER(num_documento)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' ')", "Se considera como campo vacío si contiene: NULL, \"NULL\", \"0\", \"NE\", \"NO ESPECIFICA\", \"NO TIENE\", \"NA\", \"\", \" \", o cualquier valor relacionado con la ausencia del dato.", 1, 1, "2026-06-01", None, "2026-06-01", "6f6ea82ec30aaf01e0752d5ed445ce53", "2026-06-01"),
    (4, "ND - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Número Documento", "Campo", "num_documento IS NOT NULL\nAND CASE\nWHEN UPPER(tipo_documento) IN ('TI','RC') THEN\nNOT (num_documento RLIKE '^[0-9]{10}$' AND LEFT(num_documento,1) = '1')\nWHEN UPPER(tipo_documento) = 'CC' THEN\nNOT num_documento RLIKE '^[0-9]{6,10}$'\nWHEN UPPER(tipo_documento) = 'NIT' THEN\nNOT num_documento RLIKE '^[0-9]{9,10}$'\nWHEN UPPER(tipo_documento) = 'CE' THEN\nNOT num_documento RLIKE '^[0-9]{4,7}$'\nWHEN UPPER(tipo_documento) IN ('PS','PPT') THEN\nNOT num_documento RLIKE '^[a-zA-Z0-9]{1,20}$'\nELSE FALSE\nEND", "TI y RC: numéricos, 10 dígitos, comienzan por 1. CE: numérica, 4–7 dígitos. CC: numérica, 6–10 dígitos. NIT: numérico, 9–10 dígitos con dígito verificador. PS/PPT: alfanumérico.", 2, 1, "2026-06-01", None, "2026-06-01", "4313a1dd0c3f9f552f6f6e476f6ad68d", "2026-06-01"),
    (5, "LL - UNI - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Llave única para el cliente", "Tabla", "(tipo_documento, num_documento) IN (\nSELECT tipo_documento, num_documento\nFROM {SOURCE}\nWHERE num_documento IS NOT NULL\nGROUP BY tipo_documento, num_documento\nHAVING COUNT(*) > 1\n)", "El valor del campo Número de documento no debe repetirse dentro del dominio de clientes para un mismo tipo de documento. No se permiten duplicados.", 1, 1, "2026-06-01", None, "2026-06-01", "8f5979f2766aba7de99c2c5f658a36cb", "2026-06-01"),
    (6, "PN - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Primer Nombre", "Campo", "primer_nombre IS NULL\nOR TRIM(UPPER(primer_nombre)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' ')", "El valor del campo debe: ser tipo texto, contener únicamente letras del alfabeto español (incluyendo acentos y la letra ñ), no permitir números ni caracteres especiales.", 2, 1, "2026-06-01", None, "2026-06-01", "975f63e73a89eda38ca321c92d40f9b5", "2026-06-01"),
    (7, "PN - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Primer Nombre", "Campo", "primer_nombre IS NOT NULL\nAND NOT TRIM(primer_nombre) RLIKE '^[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ ]+$'", "El campo no debe ser vacío. Se considera vacío si contiene: NULL, \"NULL\", \"0\", \"NE\", \"NO ESPECIFICA\", \"NO TIENE\", \"NA\", \"\", \" \", o cualquier valor relacionado con la ausencia del dato.", 1, 1, "2026-06-01", None, "2026-06-01", "0a0dabc5290d22c6eab8732442975ab0", "2026-06-01"),
    (8, "PA - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Primer Apellido", "Campo", "UPPER(tipo_documento) <> 'NIT'\nAND (primer_apellido IS NULL OR TRIM(UPPER(primer_apellido)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' '))", "Para registros con Tipo de documento <> 'NIT': no ser nulo, contener únicamente letras del alfabeto español (incluyendo acentos, ñ), no permitir números ni caracteres especiales.", 2, 1, "2026-06-01", None, "2026-06-01", "a43fd1afb37e556df3ebcb084ec2c9c8", "2026-06-01"),
    (9, "PA - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Primer Apellido", "Campo", "UPPER(tipo_documento) <> 'NIT'\nAND primer_apellido IS NOT NULL\nAND NOT TRIM(primer_apellido) RLIKE '^[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ ]+$'", "Para registros con Tipo de documento <> 'NIT': se considera vacío si contiene NULL, \"NULL\", \"0\", \"NE\", \"NO ESPECIFICA\", \"NO TIENE\", \"NA\", \"\", \" \".", 1, 1, "2026-06-01", None, "2026-06-01", "66d0061f44376de9572b03266b999cd8", "2026-06-01"),
    (10, "EM - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Email", "Campo", "email IS NULL\nOR TRIM(UPPER(email)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' ')", "El campo Correo electrónico debe cumplir el formato: usuario@dominio.TLD. Debe contener exactamente un @, no permitir espacios en blanco ni caracteres inválidos.", 3, 1, "2026-06-01", None, "2026-06-01", "3a8a351f2fb4a9412383720378c290aa", "2026-06-01"),
    (11, "EM - VAL - 2", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Email", "Campo", "UPPER(tipo_documento) IN ('TI','RC')\nAND (email IS NULL OR email = '')", "La parte usuario debe: estar antes del @, permitir letras/números/puntos/guiones/guion bajo, no iniciar ni terminar con punto, longitud 1–64 caracteres.", 4, 1, "2026-06-01", None, "2026-06-01", "74e52e759273eaacb117eaed3a2cf4b0", "2026-06-01"),
    (12, "EM - VAL - 3", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Email", "Campo", "email IS NOT NULL\nAND NOT email RLIKE '^[^@\\\\s]+@[^@\\\\s]+\\\\.[^@\\\\s]+$'", "La parte dominio debe: permitir letras/números/guiones, contener al menos un punto separando el TLD, longitud 4–255 caracteres.", 5, 1, "2026-06-01", None, "2026-06-01", "5540b37bd689f64ea845eb226692647b", "2026-06-01"),
    (13, "EM - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Email", "Campo", "email IS NOT NULL\nAND LOCATE('@', email) > 0\nAND NOT SUBSTRING_INDEX(email, '@', 1) RLIKE '^[a-zA-Z0-9][a-zA-Z0-9._\\\\-]{0,62}[a-zA-Z0-9]$|^[a-zA-Z0-9]$'", "Se considera vacío si contiene: NULL, \"NULL\", \"0\", \"NE\", \"NO ESPECIFICA\", \"NO TIENE\", \"NA\", \"\", \" \".", 1, 1, "2026-06-01", None, "2026-06-01", "1b30b533eb3c2bb78fedab55951352d9", "2026-06-01"),
    (14, "EM - COM - 2", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Email", "Relación entre campos", "email IS NOT NULL\nAND LOCATE('@', email) > 0\nAND NOT SUBSTRING_INDEX(email, '@', -1) RLIKE '^[a-zA-Z0-9\\\\-]+(\\\\.[a-zA-Z0-9\\\\-]+)+$'", "Para registros con Tipo de documento IN (‘TI’, ‘RC’) o edad calculada a partir de la Fecha de nacimiento < 18 años, el Correo electrónico debe ser igual al correo del responsable legal o tomador.", 2, 1, "2026-06-01", None, "2026-06-01", "408d8a71c188f7f56ea9f5989db65e0f", "2026-06-01"),
    (15, "EM - VAL - 4", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Email", "Campo", "email IS NOT NULL AND LENGTH(email) > 320", "La longitud total del correo electrónico no debe exceder 320 caracteres.", 6, 1, "2026-06-01", None, "2026-06-01", "45dfe2588bac6c3d00c42f186940bf22", "2026-06-01"),
    (16, "CEL - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Celular", "Campo", "celular IS NULL\nOR TRIM(UPPER(celular)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' ')", "El campo Celular debe ser numérico, tener longitud exacta de 10 dígitos, iniciar por 3, no contener espacios ni caracteres especiales y no incluir indicativo de país.", 3, 1, "2026-06-01", None, "2026-06-01", "ec4ba667f42f2db9366a3233142d71b6", "2026-06-01"),
    (17, "CEL - VAL - 2", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Celular", "Campo", "UPPER(tipo_documento) IN ('TI','RC')\nAND (celular IS NULL OR celular = '')", "Los tres primeros dígitos del celular deben estar en el rango 300 a 399.", 4, 1, "2026-06-01", None, "2026-06-01", "a1cde3b75da125f8be593e541f98b191", "2026-06-01"),
    (18, "CEL - VAL - 4", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Celular", "Campo", "celular IS NOT NULL\nAND NOT celular RLIKE '^3[0-9]{9}$'", "ISNUMERIC(CELULAR) = 1; CELULAR NOT LIKE '% %'; CELULAR NOT LIKE '%[^0-9]%'.", 5, 1, "2026-06-01", None, "2026-06-01", "59554d4bc00578d364bb5c29e631810a", "2026-06-01"),
    (19, "CEL - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Celular", "Campo", "celular IS NOT NULL\nAND celular RLIKE '^[0-9]{10}$'\nAND CAST(LEFT(celular, 3) AS INT) NOT BETWEEN 300 AND 399", "Se considera vacío si contiene: NULL, \"NULL\", \"0\", \"NE\", \"NO ESPECIFICA\", \"NO TIENE\", \"NA\", \"\", \" \".", 1, 1, "2026-06-01", None, "2026-06-01", "6fd8100772043a35715effca9a7e3d01", "2026-06-01"),
    (20, "CEL - COM - 2", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Celular", "Relación entre campos", "celular IS NOT NULL AND LENGTH(TRIM(celular)) <> 10", "Para registros con Tipo de documento IN (‘TI’, ‘RC’) o edad calculada a partir de la Fecha de nacimiento < 18 años, el Celular debe ser igual al celular del responsable legal o tomador.", 2, 1, "2026-06-01", None, "2026-06-01", "3b6a833412d8d3a685f080cfae3f9a1d", "2026-06-01"),
    (21, "CEL - VAL - 3", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Celular", "Campo", "celular IS NOT NULL\nAND (celular LIKE '% %' OR NOT celular RLIKE '^[0-9]+$')", "LEN(CELULAR) = 10", 6, 1, "2026-06-01", None, "2026-06-01", "d67ae52b9a1057d25fae9e4a9c7e7717", "2026-06-01"),
    (22, "DR - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Dirección de residencia", "Campo", "direccion_residencia IS NULL\nOR TRIM(UPPER(direccion_residencia)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' ')", "Se considera vacío si contiene: NULL, \"NULL\", \"0\", \"NE\", \"NO ESPECIFICA\", \"NO TIENE\", \"NA\", \"\", \" \".", 1, 1, "2026-06-01", None, "2026-06-01", "6c60f657ad42a9de22b8ceb1a896d34f", "2026-06-01"),
    (23, "DR - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Dirección de residencia", "Campo", "direccion_residencia IS NOT NULL\nAND (\nNOT direccion_residencia RLIKE '^[a-zA-Z0-9áéíóúÁÉÍÓÚñÑ #\\\\-\\\\.°]+$'\nOR NOT direccion_residencia RLIKE '[a-zA-ZáéíóúÁÉÍÓÚñÑ]'\n)", "El campo Dirección debe: ser tipo texto, contener únicamente caracteres alfanuméricos, espacios, no permitir únicamente números.", 2, 1, "2026-06-01", None, "2026-06-01", "f8041be8f29e71ab026a9dc1455b4edc", "2026-06-01"),
    (24, "DR - CON - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Dirección de residencia", "Relación entre campos", "ciudad_residencia IS NOT NULL\nAND departamento IS NOT NULL\nAND (direccion_residencia IS NULL OR TRIM(UPPER(direccion_residencia)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' '))", "Si CIUDAD_RESIDENCIA IS NOT NULL y DEPARTAMENTO IS NOT NULL, entonces DIRECCION_RESIDENCIA no debe ser nula ni vacía. Para menores de edad, la dirección debe corresponder a la del responsable legal.", 3, 1, "2026-06-01", None, "2026-06-01", "c24bbcbdf663edcca30310229ad47410", "2026-06-01"),
    (25, "CR - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Ciudad de residencia", "Campo", "ciudad_residencia IS NULL\nOR TRIM(UPPER(ciudad_residencia)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' ')", "Se considera vacío si contiene: NULL, \"NULL\", \"0\", \"NE\", \"NO ESPECIFICA\", \"NO TIENE\", \"NA\", \"\", \" \".", 1, 1, "2026-06-01", None, "2026-06-01", "530ecb5ce89cee7fb5b03de7630f5725", "2026-06-01"),
    (26, "CR - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Ciudad de residencia", "Campo", "ciudad_residencia IS NOT NULL\nAND NOT TRIM(ciudad_residencia) RLIKE '^[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ \\\\-]+$'", "El valor del campo Ciudad de residencia debe: pertenecer a la lista de referencia DIVIPOLA (DANE), contener únicamente letras del alfabeto español, no permitir números.", 2, 1, "2026-06-01", None, "2026-06-01", "91626dbabaf0c97565f6dc59adb9f842", "2026-06-01"),
    (27, "CR - CON - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Ciudad de residencia", "Relación entre campos", "departamento IS NOT NULL\nAND ciudad_residencia IS NOT NULL\nAND NOT EXISTS (\nSELECT 1 FROM referencia_divipola d\nWHERE d.departamento = departamento\nAND d.municipio    = ciudad_residencia\n)", "Si DEPARTAMENTO IS NOT NULL, CIUDAD IN Lista de referencia del departamento.", 3, 1, "2026-06-01", None, "2026-06-01", "71277bc2a9dc38dbd144a9801a4f6b4a", "2026-06-01"),
    (28, "FN - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Fecha de nacimiento", "Campo", "UPPER(tipo_documento) <> 'NIT'\nAND (fecha_nacimiento IS NULL OR TRIM(CAST(fecha_nacimiento AS STRING)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' '))", "Para registros con Tipo de documento <> 'NIT', la Fecha de nacimiento debe ser obligatoria. Se considera vacío si contiene NULL, fechas en blanco o valores no fecha.", 1, 1, "2026-06-01", None, "2026-06-01", "7ca9b1081cf0127bb152b253a70f4a79", "2026-06-01"),
    (29, "FN - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Fecha de nacimiento", "Campo", "fecha_nacimiento IS NOT NULL\nAND (\nTRY_CAST(fecha_nacimiento AS DATE) IS NULL\nOR CAST(fecha_nacimiento AS DATE) > CURRENT_DATE()\nOR DATEDIFF(CURRENT_DATE(), CAST(fecha_nacimiento AS DATE)) / 365.25 > 108\n)", "ISDATE(FECHA_NACIMIENTO) = 0 → Fecha inválida. FECHA_NACIMIENTO < DATEADD(YEAR, -108, GETDATE()) → Fuera de rango. DATEDIFF(YEAR, FECHA_NACIMIENTO, GETDATE()) > 108 → Edad no válida.", 2, 1, "2026-06-01", None, "2026-06-01", "0f23de2fe46f72a3568734ddf9dd97dd", "2026-06-01"),
    (30, "FN - RAZ - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Fecha de nacimiento", "Relación entre campos", "fecha_nacimiento IS NOT NULL\nAND DATEDIFF(CURRENT_DATE(), CAST(fecha_nacimiento AS DATE)) / 365.25 < 18\nAND UPPER(tipo_documento) = 'CC'", "Si DATEDIFF(YEAR, FECHA_NACIMIENTO, GETDATE()) < 18 (menor de edad): TIPO_DOCUMENTO debe estar en ('TI', 'RC', 'PS', 'CE', 'PPT'). Si TIPO_DOCUMENTO = 'CC' y edad < 18 → Error de consistencia.", 3, 1, "2026-06-01", None, "2026-06-01", "424466d5b98ec20f5f728765321bac4a", "2026-06-01"),
    (31, "GEN - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Género", "Campo", "UPPER(tipo_documento) <> 'NIT'\nAND (genero IS NULL OR TRIM(UPPER(genero)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' '))", "Para registros con Tipo de documento <> 'NIT', el campo Género debe ser obligatorio. Se considera vacío si contiene NULL o cualquier valor relacionado con la ausencia del dato.", 1, 1, "2026-06-01", None, "2026-06-01", "35a8ed12e8f3eda88f5b6d6e2e2a544a", "2026-06-01"),
    (32, "GEN - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Género", "Campo", "genero IS NOT NULL\nAND UPPER(TRIM(genero)) NOT IN ('F','M','N')", "GENERO NOT IN ('F', 'M', 'N') → Valor no válido. F: Femenino, M: Masculino, N: No binario / No especifica. El campo debe validarse contra la lista de referencia del catálogo.", 2, 1, "2026-06-01", None, "2026-06-01", "86eb2b06ce4f67db9cb47876bb7c318d", "2026-06-01"),
    (33, "EPS - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "EPS actual", "Campo", "UPPER(tipo_documento) <> 'NIT'\nAND (eps_actual IS NULL OR TRIM(UPPER(eps_actual)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' '))", "Para registros con Tipo de documento <> 'NIT', el campo EPS actual debe ser obligatorio. Se considera vacío si contiene NULL o cualquier valor relacionado con la ausencia del dato.", 1, 1, "2026-06-01", None, "2026-06-01", "01895fe86c57de41ebf65b9075480693", "2026-06-01"),
    (34, "EPS - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "EPS actual", "Campo", "eps_actual IS NOT NULL\nAND NOT EXISTS (\nSELECT 1 FROM referencia_eps r WHERE r.nombre_eps = eps_actual AND r.vigente = 'SI'\n)", "El valor del campo EPS debe pertenecer al listado oficial de EPS vigentes del Ministerio de Salud. Fuente: Ministerio de Salud Colombia. Valores fuera de la lista → No válido.", 2, 1, "2026-06-01", None, "2026-06-01", "b40aeb6b455f53f1f55c4f0537190a73", "2026-06-01"),
    (35, "FED - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Fecha de expedición de documento", "Campo", "UPPER(tipo_documento) <> 'NIT'\nAND (fecha_expedicion_documento IS NULL OR TRIM(CAST(fecha_expedicion_documento AS STRING)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' '))", "Se considera vacío si contiene: NULL, \"NULL\", \"0\", \"NE\", \"NO ESPECIFICA\", \"NO TIENE\", \"NA\", \"\", \" \".", 1, 1, "2026-06-01", None, "2026-06-01", "0e66f8c5e2e4fb55e08f797099cfde50", "2026-06-01"),
    (36, "FED - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Fecha de expedición de documento", "Campo", "fecha_expedicion_documento IS NOT NULL\nAND (\nTRY_CAST(fecha_expedicion_documento AS DATE) IS NULL\nOR CAST(fecha_expedicion_documento AS DATE) > CURRENT_DATE()\nOR CAST(fecha_expedicion_documento AS DATE) < ADD_MONTHS(CURRENT_DATE(), -101*12)\n)", "ISDATE(FECHA_EXPEDICION_DOCUMENTO) = 0 → Fecha inválida. FECHA_EXPEDICION_DOCUMENTO NOT BETWEEN DATEADD(YEAR, -101, GETDATE()) AND GETDATE() → Fuera de rango. No se admiten fechas futuras.", 2, 1, "2026-06-01", None, "2026-06-01", "f2f4a6158d0e821d43d06243f4ecca13", "2026-06-01"),
    (37, "FED - RAZ - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Fecha de expedición de documento", "Relación entre campos", "fecha_expedicion_documento IS NOT NULL\nAND fecha_nacimiento IS NOT NULL\nAND CAST(fecha_expedicion_documento AS DATE) < CAST(fecha_nacimiento AS DATE)", "FECHA_EXPEDICION_DOCUMENTO < FECHA_NACIMIENTO → Error de consistencia. La fecha de expedición debe ser posterior o igual a la fecha de nacimiento del cliente.", 3, 1, "2026-06-01", None, "2026-06-01", "4447557bd22cbe13a7338a81c9186b5d", "2026-06-01"),
    (38, "ATDP - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "ATDP (Autorización de Tratamiento de Datos Personales)", "Campo", "UPPER(tipo_documento) <> 'NIT'\nAND (atdp IS NULL OR TRIM(UPPER(atdp)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' '))", "Para registros con Tipo de documento <> 'NIT', el campo ATDP debe ser obligatorio. Se considera vacío si contiene NULL o cualquier valor relacionado con la ausencia del dato.", 1, 1, "2026-06-01", None, "2026-06-01", "7a09808ffd33c4742c34e492e3cd40b0", "2026-06-01"),
    (39, "ATDP - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "ATDP (Autorización de Tratamiento de Datos Personales)", "Campo", "atdp IS NOT NULL\nAND UPPER(TRIM(atdp)) NOT IN ('SI','NO')", "ATDP NOT IN ('SI', 'NO') → Valor no válido", 2, 1, "2026-06-01", None, "2026-06-01", "0cb33f826cbb956279793fde9d85daf8", "2026-06-01"),
    (40, "FATDP - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Fecha de actualización ATDP", "Campo", "UPPER(tipo_documento) <> 'NIT'\nAND atdp IS NOT NULL AND TRIM(atdp) <> ''\nAND (fecha_atdp IS NULL OR TRIM(CAST(fecha_atdp AS STRING)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' '))", "Para registros con Tipo de documento <> 'NIT', la Fecha de actualización ATDP debe ser obligatoria. Si el campo ATDP es diferente de nulo, la fecha también debe estar diligenciada.", 1, 1, "2026-06-01", None, "2026-06-01", "63936d7bb784f556838db4e943b8414f", "2026-06-01"),
    (41, "FATDP - COM - 2", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Fecha de actualización ATDP", "Relación entre campos", "(atdp IS NOT NULL AND atdp <> '' AND fecha_atdp IS NULL)\nOR (atdp IS NULL AND fecha_atdp IS NOT NULL)", "Si ATDP IS NOT NULL y ATDP <> '' entonces FECHA_ATDP debe estar diligenciada. Si ATDP IS NULL entonces FECHA_ATDP debe ser NULL.", 2, 1, "2026-06-01", None, "2026-06-01", "a6f517beba53a22f466bdb2cc3558d85", "2026-06-01"),
    (42, "FATDP - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Fecha de actualización ATDP", "Campo", "fecha_atdp IS NOT NULL\nAND (\nTRY_CAST(fecha_atdp AS DATE) IS NULL\nOR CAST(fecha_atdp AS DATE) > CURRENT_DATE()\n)", "ISDATE(FECHA_ATDP) = 0 → Fecha inválida. FECHA_ATDP NOT BETWEEN '1800-01-01' AND GETDATE() → Fuera de rango. No se admiten fechas futuras.", 3, 1, "2026-06-01", None, "2026-06-01", "c82b852b4139420da783d7129507e5ea", "2026-06-01"),
    (43, "FATDP - RAZ - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Fecha de actualización ATDP", "Relación entre campos", "fecha_atdp IS NOT NULL AND fecha_nacimiento IS NOT NULL\nAND CAST(fecha_atdp AS DATE) < CAST(fecha_nacimiento AS DATE)", "FECHA_ATDP no debe ser anterior a FECHA_NACIMIENTO del cliente.", 4, 1, "2026-06-01", None, "2026-06-01", "01760be523132190ca0857180e55c0aa", "2026-06-01"),
    (44, "PC - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Preferencia de contacto (Ley 2300)", "Campo", "UPPER(tipo_documento) <> 'NIT'\nAND (preferencia_contacto IS NULL OR TRIM(UPPER(preferencia_contacto)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' '))", "Para registros con Tipo de documento <> 'NIT', el campo Preferencia de contacto debe ser obligatorio. Se considera vacío si contiene NULL o cualquier valor relacionado con la ausencia del dato.", 1, 1, "2026-06-01", None, "2026-06-01", "171fb74813dfb8d971e3203defed6f21", "2026-06-01"),
    (45, "PC - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Preferencia de contacto (Ley 2300)", "Campo", "preferencia_contacto IS NOT NULL\nAND UPPER(TRIM(preferencia_contacto)) NOT IN ('EMAIL','CELULAR','TELEFONO','CORREO_POSTAL','NINGUNO')", "El campo Preferencia de contacto debe pertenecer a la lista de referencia: 'EMAIL', 'CELULAR', 'TELEFONO', 'CORREO_POSTAL', 'NINGUNO'. No se permiten valores distintos a los de la lista.", 2, 1, "2026-06-01", None, "2026-06-01", "b31e04128d4694b5cf64baaa2d69f63d", "2026-06-01"),
    (46, "FMC - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Fecha Medio de contacto", "Campo", "preferencia_contacto IS NOT NULL AND TRIM(preferencia_contacto) <> ''\nAND (fecha_medio_contacto IS NULL OR TRIM(CAST(fecha_medio_contacto AS STRING)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' '))", "Si el campo Preferencia de contacto está diligenciado, la Fecha Medio de contacto debe ser obligatoria. Se considera vacío si contiene NULL o valores en blanco.", 1, 1, "2026-06-01", None, "2026-06-01", "fdc7c182e7d163cd213d9714c8ee3f0c", "2026-06-01"),
    (47, "FMC - COM - 2", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Fecha Medio de contacto", "Relación entre campos", "preferencia_contacto IS NOT NULL AND preferencia_contacto <> ''\nAND fecha_medio_contacto IS NULL", "Si PREFERENCIA_CONTACTO IS NOT NULL y <> '' entonces FECHA_MEDIO_CONTACTO debe estar diligenciada. ", 2, 1, "2026-06-01", None, "2026-06-01", "3bba23e3ba55168b27746f166ee6108c", "2026-06-01"),
    (48, "FMC - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Fecha Medio de contacto", "Campo", "fecha_medio_contacto IS NOT NULL\nAND (\nTRY_CAST(fecha_medio_contacto AS DATE) IS NULL\nOR CAST(fecha_medio_contacto AS DATE) > CURRENT_DATE()\n)", "ISDATE(FECHA_MEDIO_CONTACTO) = 0 → Fecha inválida. FECHA_MEDIO_CONTACTO NOT BETWEEN '1800-01-01' AND GETDATE() → Fuera de rango. No se admiten fechas futuras.", 3, 1, "2026-06-01", None, "2026-06-01", "d42d04d7d95cb443ab7369555544eaa9", "2026-06-01"),
    (49, "FMC - RAZ - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Fecha Medio de contacto", "Relación entre campos", "fecha_medio_contacto IS NOT NULL AND fecha_nacimiento IS NOT NULL\nAND CAST(fecha_medio_contacto AS DATE) < CAST(fecha_nacimiento AS DATE)", " FECHA_MEDIO_CONTACTO no debe ser anterior a FECHA_NACIMIENTO del cliente.", 4, 1, "2026-06-01", None, "2026-06-01", "abcd1263341944ed0cb273df75d8ce82", "2026-06-01"),
    (50, "ATDPC - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "ATDP Comercial", "Campo", "UPPER(tipo_documento) <> 'NIT'\nAND (atdp_comercial IS NULL OR TRIM(UPPER(atdp_comercial)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' '))", "Para registros con Tipo de documento <> 'NIT', el campo ATDP Comercial debe estar diligenciado. Se considera vacío si contiene NULL o valores en blanco.", 1, 1, "2026-06-01", None, "2026-06-01", "2d9263f10dfa04f117a4f387e020dd6f", "2026-06-01"),
    (51, "ATDPC - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "ATDP Comercial", "Campo", "atdp_comercial IS NOT NULL\nAND UPPER(TRIM(atdp_comercial)) NOT IN ('SI','NO')", "ATDP_COMERCIAL NOT IN ('SI', 'NO') → Valor no válido. El campo debe validarse contra la lista de referencia específica del campo.", 2, 1, "2026-06-01", None, "2026-06-01", "3be870c865fc9c3ae838e13105b625a8", "2026-06-01"),
    (52, "FATDPC - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Fecha de actualización ATDP Comercial", "Campo", "atdp_comercial IS NOT NULL AND TRIM(atdp_comercial) <> ''\nAND (fecha_atdp_comercial IS NULL OR TRIM(CAST(fecha_atdp_comercial AS STRING)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' '))", "Si el campo ATDP Comercial está diligenciado, la Fecha de actualización ATDP Comercial debe ser obligatoria. Se considera vacío si contiene NULL o valores en blanco.", 1, 1, "2026-06-01", None, "2026-06-01", "2aac5379291bf8101acb60f348a2e194", "2026-06-01"),
    (53, "FATDPC - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Fecha de actualización ATDP Comercial", "Campo", "(atdp_comercial IS NOT NULL AND atdp_comercial <> '' AND fecha_atdp_comercial IS NULL)\nOR (atdp_comercial IS NULL AND fecha_atdp_comercial IS NOT NULL)", "ISDATE(FECHA_ATDP_COMERCIAL) = 0 → Fecha inválida. FECHA_ATDP_COMERCIAL NOT BETWEEN '1800-01-01' AND GETDATE() → Fuera de rango. No se admiten fechas futuras.", 3, 1, "2026-06-01", None, "2026-06-01", "4fdf943c49f9386c84ef17a7a454360b", "2026-06-01"),
    (54, "FATDPC - COM - 2", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Fecha de actualización ATDP Comercial", "Relación entre campos", "fecha_atdp_comercial IS NOT NULL\nAND (\nTRY_CAST(fecha_atdp_comercial AS DATE) IS NULL\nOR CAST(fecha_atdp_comercial AS DATE) > CURRENT_DATE()\n)", "Si ATDP_COMERCIAL IS NOT NULL y <> '' entonces FECHA_ATDP_COMERCIAL debe estar diligenciada. Si ATDP_COMERCIAL IS NULL entonces FECHA_ATDP_COMERCIAL debe ser NULL.", 2, 1, "2026-06-01", None, "2026-06-01", "05ccdea241dad31d859f95c7b12fed73", "2026-06-01"),
    (55, "TP - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Tipo de persona", "Campo", "tipo_persona IS NULL\nOR TRIM(UPPER(tipo_persona)) IN ('NULL','NE','NO ESPECIFICA','',' ')", "Se considera como campo vacío si contiene: NULL, \"NULL\", \"NE\", \"NO ESPECIFICA\", \"\", \" \". El campo debe estar diligenciado en el 100% de los registros independientemente del canal de captura.", 1, 1, "2026-06-01", None, "2026-06-01", "752bf49911f4fa58433d9f31bb6f6198", "2026-06-01"),
    (56, "TP - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Tipo de persona", "Campo", "tipo_persona IS NOT NULL\nAND UPPER(TRIM(tipo_persona)) NOT IN ('NATURAL','JURIDICA','N','J')", "TIPO_PERSONA NOT IN ('NATURAL', 'JURIDICA') → Valor no válido. Equivalencias aceptadas en catálogo: N / NATURAL, J / JURIDICA. El campo debe validarse contra la tabla de referencia maestra del sistema.", 2, 1, "2026-06-01", None, "2026-06-01", "18897ed9dea27b2df343f3fef5ad374a", "2026-06-01"),
    (57, "TP - RAZ - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Tipo de persona", "Relación entre campos", "(UPPER(tipo_persona) IN ('JURIDICA','J') AND UPPER(tipo_documento) <> 'NIT')\nOR (UPPER(tipo_persona) IN ('NATURAL','N')  AND UPPER(tipo_documento) = 'NIT')", "Si TIPO_PERSONA = 'JURIDICA' entonces TIPO_DOCUMENTO debe ser 'NIT'. Si TIPO_PERSONA = 'NATURAL' entonces TIPO_DOCUMENTO NOT IN ('NIT').", 3, 1, "2026-06-01", None, "2026-06-01", "ba5affe8c1b735132ce57086d09a60c4", "2026-06-01"),
    (58, "EC - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Estado civil", "Campo", "UPPER(tipo_documento) = 'CC'\nAND (estado_civil IS NULL OR TRIM(UPPER(estado_civil)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' '))", "Para registros con Tipo de documento = 'CC' (mayor de edad), el campo Estado civil debe ser obligatorio. Se considera vacío si contiene: NULL, \"NULL\", \"NE\", \"NO ESPECIFICA\", \"NA\", \"\", \" \".", 1, 1, "2026-06-01", None, "2026-06-01", "b6aa2e56bb31c260e6f6950db63cc081", "2026-06-01"),
    (59, "EC - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Estado civil", "Campo", "estado_civil IS NOT NULL\nAND UPPER(TRIM(estado_civil)) NOT IN ('SOLTERO','CASADO','UNION_LIBRE','DIVORCIADO','VIUDO','SEPARADO')", "ESTADO_CIVIL NOT IN ('SOLTERO', 'CASADO', 'UNION_LIBRE', 'DIVORCIADO', 'VIUDO', 'SEPARADO') → Valor no válido. El campo debe validarse contra la lista de referencia maestra del catálogo de estado civil.", 2, 1, "2026-06-01", None, "2026-06-01", "dededd49dd5804b11f3f01df6edf31cc", "2026-06-01"),
    (60, "AE - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Actividad económica", "Campo", "UPPER(tipo_documento) = 'NIT'\nAND (actividad_economica IS NULL OR TRIM(UPPER(actividad_economica)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' '))", "Para registros con Tipo de documento = 'NIT' o productos de riesgo ocupacional, el campo Actividad económica debe ser obligatorio. Se considera vacío si contiene: NULL, \"NULL\", \"NE\", \"NO ESPECIFICA\", \"NA\", \"\", \" \".", 1, 1, "2026-06-01", None, "2026-06-01", "2c4f29726dd3ecd427135d234f3c914a", "2026-06-01"),
    (61, "AE - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Actividad económica", "Campo", "actividad_economica IS NOT NULL\nAND NOT actividad_economica RLIKE '^[0-9]{4}$'", "El valor del campo Actividad económica debe pertenecer a la tabla de referencia CIIU Rev. 4 A.C. del DANE. Fuente: DANE Colombia. Valores fuera de la lista → No válido. El código debe ser numérico de 4 dígitos.", 2, 1, "2026-06-01", None, "2026-06-01", "2f88aa3fba07ff5d1bb39054693ea0c1", "2026-06-01"),
    (62, "DPTO - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Departamento", "Campo", "direccion_residencia IS NOT NULL AND TRIM(direccion_residencia) <> ''\nAND (departamento IS NULL OR TRIM(UPPER(departamento)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' '))", "Se considera vacío si contiene: NULL, \"NULL\", \"NE\", \"NO ESPECIFICA\", \"NO TIENE\", \"NA\", \"\", \" \". Obligatorio para el 100% de los registros con dirección de residencia diligenciada.", 1, 1, "2026-06-01", None, "2026-06-01", "2c86898977256eb0008cc5ec8076b2d6", "2026-06-01"),
    (63, "DPTO - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Departamento", "Campo", "departamento IS NOT NULL\nAND NOT TRIM(departamento) RLIKE '^[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ \\\\-]+$'", "El valor del campo Departamento debe pertenecer a la lista de referencia DIVIPOLA (DANE), contener únicamente letras del alfabeto español, espacios y guiones. No se permiten números ni caracteres especiales.", 2, 1, "2026-06-01", None, "2026-06-01", "1df87bb1dac87de21a9ae4979702866f", "2026-06-01"),
    (64, "DPTO - CON - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Departamento", "Relación entre campos", "UPPER(pais) = 'COLOMBIA'\nAND departamento IS NOT NULL\nAND NOT EXISTS (\nSELECT 1 FROM referencia_divipola d\nWHERE d.departamento = departamento\n)", "Si PAIS = 'COLOMBIA' entonces DEPARTAMENTO debe pertenecer a la tabla DIVIPOLA DANE. CIUDAD_RESIDENCIA debe pertenecer al DEPARTAMENTO indicado según DIVIPOLA.", 3, 1, "2026-06-01", None, "2026-06-01", "ae61ba4463fb5deb5d7855c83a5121fb", "2026-06-01"),
    (65, "PAIS - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "País", "Campo", "pais IS NULL\nOR TRIM(UPPER(pais)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' ')", "Se considera vacío si contiene: NULL, \"NULL\", \"NE\", \"NO ESPECIFICA\", \"NO TIENE\", \"NA\", \"\", \" \". Obligatorio para todos los registros.", 1, 1, "2026-06-01", None, "2026-06-01", "d38bf094901ff68462fc6212edc25a0f", "2026-06-01"),
    (66, "PAIS - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "País", "Campo", "pais IS NOT NULL\nAND NOT EXISTS (\nSELECT 1 FROM referencia_iso3166 p WHERE p.nombre_pais = UPPER(pais) OR p.codigo_alpha2 = UPPER(pais) OR p.codigo_alpha3 = UPPER(pais)\n)", "El valor del campo País debe pertenecer a la lista ISO 3166-1 alpha-2 o alpha-3 (nombre del país o código). Valores fuera de la lista → No válido. El catálogo debe mantenerse actualizado según ISO 3166-1 vigente.", 2, 1, "2026-06-01", None, "2026-06-01", "c11bfbc67fdd2b680738a059f0461908", "2026-06-01"),
    (67, "ROL - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Rol", "Campo", "rol IS NULL\nOR TRIM(UPPER(rol)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' ')", "Se considera vacío si contiene: NULL, \"NULL\", \"NE\", \"NO ESPECIFICA\", \"NA\", \"\", \" \". Obligatorio para el 100% de los registros de personas vinculadas a un contrato.", 1, 1, "2026-06-01", None, "2026-06-01", "8eb0cb3dfa62e3130bf15f5d3125017e", "2026-06-01"),
    (68, "ROL - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Rol", "Campo", "rol IS NOT NULL\nAND UPPER(TRIM(rol)) NOT IN ('TOMADOR','ASEGURADO','BENEFICIARIO','ASEGURADO_BENEFICIARIO','TITULAR')", "EJEMPLO: ROL NOT IN ('TOMADOR', 'ASEGURADO', 'BENEFICIARIO', 'ASEGURADO_BENEFICIARIO', 'TITULAR') → Valor no válido. El campo debe validarse contra la tabla de referencia maestra del sistema.", 2, 1, "2026-06-01", None, "2026-06-01", "d00cfa46f68629d4eec763df3e1b563f", "2026-06-01"),
    (69, "TC - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Tipo de contrato", "Campo", "tipo_contrato IS NULL\nOR TRIM(UPPER(tipo_contrato)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' ')", "Se considera vacío si contiene: NULL, \"NULL\", \"NE\", \"NO ESPECIFICA\", \"NA\", \"\", \" \". Obligatorio para el 100% de los registros de contrato.", 1, 1, "2026-06-01", None, "2026-06-01", "d2f89ba4720c8b490adcfb473339b143", "2026-06-01"),
    (70, "TC - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Tipo de contrato", "Campo", "tipo_contrato IS NOT NULL\nAND UPPER(TRIM(tipo_contrato)) NOT IN ('INDIVIDUAL','COLECTIVO','FAMILIAR','GRUPAL')", "TIPO_CONTRATO NOT IN ('INDIVIDUAL', 'COLECTIVO', 'FAMILIAR', 'GRUPAL') → Valor no válido. El campo debe validarse contra la tabla de referencia maestra del sistema.", 2, 1, "2026-06-01", None, "2026-06-01", "ec7485ece4358b672f7da4e9a4b01e8a", "2026-06-01"),
    (71, "PLAN - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Plan", "Campo", "plan IS NULL\nOR TRIM(UPPER(plan)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' ')", "Se considera vacío si contiene: NULL, \"NULL\", \"NE\", \"NO ESPECIFICA\", \"NA\", \"\", \" \". Obligatorio para el 100% de los registros de contrato.", 1, 1, "2026-06-01", None, "2026-06-01", "a15b47bbd4247862d799643253bd8097", "2026-06-01"),
    (72, "PLAN - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Plan", "Campo", "plan IS NOT NULL\nAND NOT EXISTS (\nSELECT 1 FROM catalogo_planes p WHERE p.codigo_plan = plan AND p.estado = 'VIGENTE'\n)", "El valor del campo Plan debe pertenecer al catálogo vigente de productos autorizados. PLAN NOT IN (SELECT CODIGO_PLAN FROM CATALOGO_PLANES WHERE ESTADO = 'VIGENTE') → Valor no válido.", 2, 1, "2026-06-01", None, "2026-06-01", "b71c829e86b4fbcaed5c4a9b8a76e38c", "2026-06-01"),
    (73, "PLAN - CON - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Plan", "Relación entre campos", "plan IS NOT NULL AND ramo IS NOT NULL\nAND NOT EXISTS (\nSELECT 1 FROM catalogo_planes p\nWHERE p.codigo_plan = plan AND p.ramo = ramo\n)", "PLAN debe pertenecer a los planes habilitados para el TIPO_CONTRATO y RAMO registrado. Si RAMO = 'ARL' entonces PLAN debe pertenecer al catálogo ARL. Si RAMO = 'VIDA' entonces PLAN debe pertenecer al catálogo VIDA.", 3, 1, "2026-06-01", None, "2026-06-01", "d70f4bf419cc5d04185f24012452b71c", "2026-06-01"),
    (74, "CONT - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Contrato", "Campo", "contrato IS NULL\nOR TRIM(UPPER(contrato)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' ')", "Se considera vacío si contiene: NULL, \"NULL\", \"0\", \"NE\", \"NO ESPECIFICA\", \"NA\", \"\", \" \". Obligatorio para el 100% de los registros activos y cancelados.", 1, 1, "2026-06-01", None, "2026-06-01", "0c21ef64003fdebe0a14ca36809cc43d", "2026-06-01"),
    (75, "CONT - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Contrato", "Campo", "contrato IS NOT NULL\nAND (contrato LIKE '% %' OR NOT contrato RLIKE '^[a-zA-Z0-9\\\\-]+$')", "El campo Contrato debe: ser alfanumérico, tener la longitud definida por el sistema (según ramo), no contener espacios en blanco ni caracteres especiales. El patrón debe definirse por catálogo por cada línea de negocio.", 2, 1, "2026-06-01", None, "2026-06-01", "bfede8d49b3b57087ecb057096ac7ea7", "2026-06-01"),
    (76, "CONT - UNI - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Contrato", "Tabla", "(contrato, ramo) IN (\nSELECT contrato, ramo FROM {SOURCE}\nWHERE contrato IS NOT NULL\nGROUP BY contrato, ramo HAVING COUNT(*) > 1\n)", "El valor del campo Contrato no debe repetirse dentro de la misma línea de negocio (RAMO) y compañía. SELECT CONTRATO, COUNT(*) FROM POLIZAS GROUP BY CONTRATO HAVING COUNT(*) > 1 → Duplicado detectado.", 3, 1, "2026-06-01", None, "2026-06-01", "b3a5e478f1252b27f9ed610794f237ec", "2026-06-01"),
    (77, "ASE - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Asesor", "Campo", "asesor IS NULL\nOR TRIM(UPPER(asesor)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' ')", "Se considera vacío si contiene: NULL, \"NULL\", \"0\", \"NE\", \"NO ESPECIFICA\", \"NA\", \"\", \" \". Obligatorio para todos los contratos en todos los ramos.", 1, 1, "2026-06-01", None, "2026-06-01", "b517410eb0dc5ad3696f6509c1f6ca12", "2026-06-01"),
    (78, "ASE - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Asesor", "Campo", "asesor IS NOT NULL\nAND NOT EXISTS (\nSELECT 1 FROM maestro_asesores a\nWHERE a.codigo_asesor = asesor AND a.estado = 'ACTIVO'\n)", "ASE NOT IN (SELECT CODIGO_ASESOR FROM MAESTRO_ASESORES WHERE ESTADO = 'ACTIVO') → Asesor no válido. El asesor debe tener vigente su autorización o habilitación según el ramo de la póliza (Resolución RUS).", 2, 1, "2026-06-01", None, "2026-06-01", "5336330278bf8d2f9cec299ecbe31501", "2026-06-01"),
    (79, "EST - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Estado", "Campo", "estado IS NULL\nOR TRIM(UPPER(estado)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' ')", "Se considera vacío si contiene: NULL, \"NULL\", \"NE\", \"NO ESPECIFICA\", \"NA\", \"\", \" \". Obligatorio para el 100% de los registros de contratos.", 1, 1, "2026-06-01", None, "2026-06-01", "bbf6f8b90406d28982661adb743f34ed", "2026-06-01"),
    (80, "EST - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Estado", "Campo", "estado IS NOT NULL\nAND UPPER(TRIM(estado)) NOT IN ('ACTIVO','INACTIVO','CANCELADO','SUSPENDIDO','EN_TRAMITE','VENCIDO')", "ESTADO NOT IN ('ACTIVO', 'INACTIVO', 'CANCELADO', 'SUSPENDIDO', 'EN_TRAMITE', 'VENCIDO') → Valor no válido. El campo debe validarse contra la tabla de referencia maestra del catálogo de estados.", 2, 1, "2026-06-01", None, "2026-06-01", "76f25ba8f5c1d5c56b9e031741a69bbe", "2026-06-01"),
    (81, "EST - RAZ - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Estado", "Relación entre campos", "estado IS NOT NULL AND fecha_fin_vigencia IS NOT NULL\nAND (\n(CAST(fecha_fin_vigencia AS DATE) < CURRENT_DATE() AND UPPER(estado) = 'ACTIVO')\nOR (CAST(fecha_inicio_vigencia AS DATE) > CURRENT_DATE() AND UPPER(estado) NOT IN ('EN_TRAMITE','INACTIVO'))\n)", "Si FECHA_FIN_VIGENCIA < GETDATE() entonces ESTADO <> 'ACTIVO'. Si FECHA_INICIO_VIGENCIA > GETDATE() entonces ESTADO = 'EN_TRAMITE' o 'INACTIVO'. Si FECHA_INICIO_VIGENCIA <= GETDATE() y FECHA_FIN_VIGENCIA >= GETDATE() entonces ESTADO = 'ACTIVO'.", 3, 1, "2026-06-01", None, "2026-06-01", "1860b7da17caf0ec283acec5b114fd4c", "2026-06-01"),
    (82, "FIV - COM - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Fecha inicio de vigencia", "Campo", "fecha_inicio_vigencia IS NULL\nOR TRIM(CAST(fecha_inicio_vigencia AS STRING)) IN (NULL, 'NULL', '0', 'NE', 'NO ESPECIFICA', 'NO TIENE', 'NA', '', ' ')", "Se considera vacío si contiene: NULL, \"NULL\", \"0\", \"NE\", \"NO ESPECIFICA\", \"NA\", \"\", \" \". Obligatorio para el 100% de los contratos en todos los estados.", 1, 1, "2026-06-01", None, "2026-06-01", "1536c77aa1be246337a9c10468ace19f", "2026-06-01"),
    (83, "FIV - VAL - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Fecha inicio de vigencia", "Campo", "fecha_inicio_vigencia IS NOT NULL\nAND (\nTRY_CAST(fecha_inicio_vigencia AS DATE) IS NULL\nOR CAST(fecha_inicio_vigencia AS DATE) < ADD_MONTHS(CURRENT_DATE(), -60)\nOR CAST(fecha_inicio_vigencia AS DATE) > ADD_MONTHS(CURRENT_DATE(), 12)\n)", "ISDATE(FECHA_INICIO_VIGENCIA) = 0 → Fecha inválida. FECHA_INICIO_VIGENCIA NOT BETWEEN DATEADD(YEAR, -5, GETDATE()) AND DATEADD(YEAR, 1, GETDATE()) → Fuera de rango permitido. No se admiten formatos distintos a YYYY-MM-DD.", 2, 1, "2026-06-01", None, "2026-06-01", "161104c421d91b38d7c0f4e522d6dcd3", "2026-06-01"),
    (84, "FIV - CON - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Fecha inicio de vigencia", "Relación entre campos", "fecha_inicio_vigencia IS NOT NULL AND fecha_fin_vigencia IS NOT NULL\nAND (\nCAST(fecha_inicio_vigencia AS DATE) >= CAST(fecha_fin_vigencia AS DATE)\nOR (UPPER(estado) = 'ACTIVO'    AND CAST(fecha_inicio_vigencia AS DATE) > CURRENT_DATE())\nOR (UPPER(estado) = 'EN_TRAMITE' AND CAST(fecha_inicio_vigencia AS DATE) <= CURRENT_DATE())\n)", "FECHA_INICIO_VIGENCIA >= FECHA_FIN_VIGENCIA (inicio debe ser anterior al fin). Si ESTADO = 'ACTIVO' entonces FECHA_INICIO_VIGENCIA <= GETDATE(). Si ESTADO = 'EN_TRAMITE' entonces FECHA_INICIO_VIGENCIA > GETDATE().", 3, 1, "2026-06-01", None, "2026-06-01", "d78e8d5067207c79187ca9fdec38d7d5", "2026-06-01"),
    (85, "FIV - OP - 1", "uc-axa-cli.silver.sv_sat_arl, uc-axa-cli.silver.sv_sat_beyond_health, uc-axa-cli.silver.sv_sat_pyc", "Fecha inicio de vigencia", "Campo", "fecha_inicio_vigencia IS NOT NULL\nAND CAST(fecha_inicio_vigencia AS DATE) < ADD_MONTHS(CURRENT_DATE(), -60)\nAND UPPER(estado) = 'ACTIVO'", "Si FECHA_INICIO_VIGENCIA < DATEADD(YEAR, -5, GETDATE()) y no existe registro de renovación en HISTORICO_CONTRATOS → Dato potencialmente desactualizado. Generar alerta de revisión. El umbral de 5 años debe ser parametrizable por ramo.", 4, 1, "2026-06-01", None, "2026-06-01", "388ba7e094166c01f50cb719c8660159", "2026-06-01")
]

df_rules = spark.createDataFrame(RAW_DATA, schema=SCHEMA)
print(f"Reglas preparadas: {df_rules.count()}")
df_rules.show(5, truncate=60)

# COMMAND ----------
# MAGIC %md
# MAGIC ## Bloque 3 — Crear tabla si no existe

def table_exists(tbl):
    try:
        spark.sql(f"DESCRIBE TABLE {tbl}")
        return True
    except Exception:
        return False

if not table_exists(TARGET):
    df_rules.limit(0).createOrReplaceTempView("_reglas_schema_ref")
    spark.sql(f"""
        CREATE TABLE {TARGET}
        USING DELTA
        TBLPROPERTIES ('delta.enableChangeDataFeed' = 'true')
        AS SELECT * FROM _reglas_schema_ref
    """)
    spark.catalog.dropTempView("_reglas_schema_ref")
    print("Tabla creada.")
else:
    print("Tabla ya existe — se usará MERGE.")

# COMMAND ----------
# MAGIC %md
# MAGIC ## Bloque 4 — MERGE (upsert por pk_regla_calidad)

df_rules.createOrReplaceTempView("_reglas_staging")

spark.sql(f"""
MERGE INTO {TARGET} AS tgt
USING _reglas_staging AS src
  ON tgt.pk_regla_calidad = src.pk_regla_calidad
WHEN MATCHED AND tgt.hash_registro <> src.hash_registro THEN
  UPDATE SET
    tgt.tabla               = src.tabla,
    tgt.atributo            = src.atributo,
    tgt.tipo_regla          = src.tipo_regla,
    tgt.regla               = src.regla,
    tgt.grupo_regla         = src.grupo_regla,
    tgt.prioridad_regla     = src.prioridad_regla,
    tgt.estado_regla        = src.estado_regla,
    tgt.fecha_ini_vigencia  = src.fecha_ini_vigencia,
    tgt.fecha_fin_vigencia  = src.fecha_fin_vigencia,
    tgt.fecha_actualizacion = src.fecha_actualizacion,
    tgt.hash_registro       = src.hash_registro,
    tgt.fecha_creacion      = src.fecha_creacion
WHEN NOT MATCHED THEN
  INSERT (sk_regla_calidad, pk_regla_calidad, tabla, atributo, tipo_regla,
          regla, grupo_regla, prioridad_regla, estado_regla,
          fecha_ini_vigencia, fecha_fin_vigencia, fecha_actualizacion,
          hash_registro, fecha_creacion)
  VALUES (src.sk_regla_calidad, src.pk_regla_calidad, src.tabla, src.atributo, src.tipo_regla,
          src.regla, src.grupo_regla, src.prioridad_regla, src.estado_regla,
          src.fecha_ini_vigencia, src.fecha_fin_vigencia, src.fecha_actualizacion,
          src.hash_registro, src.fecha_creacion)
""")

spark.catalog.dropTempView("_reglas_staging")
print("MERGE completado.")

# COMMAND ----------
# MAGIC %md
# MAGIC ## Bloque 5 — Validación post-carga

total  = spark.sql(f"SELECT COUNT(*) AS n FROM {TARGET}").collect()[0]["n"]
nullpk = spark.sql(f"SELECT COUNT(*) AS n FROM {TARGET} WHERE pk_regla_calidad IS NULL").collect()[0]["n"]
duppk  = spark.sql(f"""
    SELECT COUNT(*) AS n FROM (
        SELECT pk_regla_calidad FROM {TARGET}
        GROUP BY pk_regla_calidad HAVING COUNT(*) > 1
    )
""").collect()[0]["n"]

print("=" * 55)
print("  VALIDACIÓN POST-CARGA")
print("=" * 55)
print(f"  Registros en tabla    : {total:>5}  (esperado: 85)")
print(f"  pk nulos              : {nullpk:>5}   {'✓' if nullpk == 0 else '✗ REVISAR'}")
print(f"  pk duplicados         : {duppk:>5}   {'✓' if duppk == 0 else '✗ REVISAR'}")

print("\n  Distribución por tipo_regla:")
spark.sql(f"""
    SELECT tipo_regla, COUNT(*) AS total
    FROM {TARGET}
    GROUP BY tipo_regla ORDER BY total DESC
""").show(truncate=False)

print("  Muestra (10 filas):")
display(spark.sql(f"SELECT * FROM {TARGET} LIMIT 10"))
